gText_Singulo_Welcome::
	.string "Welcome to POKéMON Emerald Odyssey!\p"
	.string "My name is SINGULO.\p"
	.string "$"

gText_Singulo_Dream::
	.string "I've always wanted to play a POKéMON\n"
	.string "game where you can catch 'em all!\p"
	.string "But it's so difficult to do it in one\n"
	.string "game across multiple regions...\p"
	.string "So this is my attempt at making it\n"
	.string "happen!\p"
	.string "I hope you like it!\p"
	.string "$"

gText_Singulo_SelectTime::
	.string "What time is it right now?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Let's make your character.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "And what's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Thanks! You should be all set!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "That should be everything!\p"
	.string "Enjoy exploring the mysterious world of\n"
	.string "POKéMON!\p"
	.string "Come find me again soon and we can\n"
	.string "chat!\p"
	.string "$"
